// Copyright (c) 2018-2024 Dr. Colin Hirsch and Daniel Frey
// Please see LICENSE for license or visit https://github.com/taocpp/config/

#ifndef TAO_CONFIG_INTERNAL_CONCAT_HPP
#define TAO_CONFIG_INTERNAL_CONCAT_HPP

#include <cstddef>
#include <cstdint>
#include <iterator>
#include <list>
#include <stdexcept>
#include <string>
#include <utility>

#include "constants.hpp"
#include "entry_kind.hpp"
#include "forward.hpp"
#include "json.hpp"
#include "key1.hpp"
#include "pegtl.hpp"

namespace tao::config::internal
{
   template< typename E >
   struct basic_concat
   {
      using data_t = std::list< E >;
      using iterator_t = typename std::list< E >::iterator;

      basic_concat() = delete;

      explicit basic_concat( const pegtl::position& p )
         : position( p )
      {}

      basic_concat( basic_concat&& ) = default;
      basic_concat( const basic_concat& ) = default;

      ~basic_concat() = default;

      basic_concat& operator=( basic_concat&& ) = default;
      basic_concat& operator=( const basic_concat& ) = default;

      [[nodiscard]] bool omit_from_final_result() const noexcept
      {
         return implicit || temporary || concat.empty();
      }

      template< typename T >
      void back_ensure_init( const T k, const pegtl::position& p )
      {
         if( concat.empty() ) {
            concat.emplace_back( k, p );
         }
         else if( concat.back().kind() != T::kind ) {
            concat.emplace_back( k, p );
         }
      }

      void back_emplace_func( const std::string& name, const pegtl::position& p )
      {
         back_ensure_init( array_init, p );
         concat.back().get_array().function = name;
      }

      [[nodiscard]] const pegtl::position& get_position() const noexcept
      {
         return position;
      }

      bool remove = false;     // Whether generated by += (false) or by = (true), because in the latter case everything that comes before must be removed.
      bool implicit = false;   // Whether implicitly generated by a delete, e.g. a.b.c = delete when a.b doesn't even exist, so it's implicitly generated to set the remove flag on a.b.c.
      bool temporary = false;  // Whether flagged as temporary by the user, i.e. this is not to be included in the final result and will be omitted by phase3.

      std::uint64_t generation = 0;

      std::list< E > concat;
      pegtl::position position;
   };

}  // namespace tao::config::internal

#endif
